### ISSUE TITLE
how in the world did u get these?

### ISSUE THREAD

**Issue by SharkyMantisGD** [Thing3487/Blooket-Cheats-2.0-#6]
how did you get all the scripts before it was deleted???!!! Do u know minesraft2?

**Comment by LeozaCEO2** [comment]
I recognize thing3487 from minesraft's repository/

**Comment by LeozaCEO2** [comment]
some dumbass is gonna think he's a skid

**Comment by Thing3487** [comment]
> how did you get all the scripts before it was deleted???!!! Do u know minesraft2?

I saved some scripts cause i contributed to repo before it was deleted.
